/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrousRouteImport } from './routes/trous'
import { Route as StudiosRouteImport } from './routes/studios'
import { Route as StaffAppRouteImport } from './routes/staff-app'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignalementsRouteImport } from './routes/signalements'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReglesScoringRouteImport } from './routes/regles-scoring'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as PointageRouteImport } from './routes/pointage'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormationRouteImport } from './routes/formation'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as DimonaRouteImport } from './routes/dimona'
import { Route as DemandesRouteImport } from './routes/demandes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContingentsRouteImport } from './routes/contingents'
import { Route as ClotureRouteImport } from './routes/cloture'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffIdRouteImport } from './routes/staff.$id'
import { Route as StaffAppPropositionsRouteImport } from './routes/staff-app_.propositions'
import { Route as PlanningGenerateRouteImport } from './routes/planning.generate'
import { Route as FormationCourseIdRouteImport } from './routes/formation.$courseId'
import { Route as DisplayStudioIdRouteImport } from './routes/display.$studioId'
import { Route as AdminSeederRouteImport } from './routes/admin.seeder'
import { Route as AdminSeedRouteImport } from './routes/admin.seed'
import { Route as AdminQaTestSuiteRouteImport } from './routes/admin.qa-test-suite'
import { Route as AdminMigrateStudiosRouteImport } from './routes/admin.migrate-studios'
import { Route as AdminIntegrityReportRouteImport } from './routes/admin.integrity-report'
import { Route as AdminHardcodingAuditRouteImport } from './routes/admin.hardcoding-audit'
import { Route as AdminDiagnosticRouteImport } from './routes/admin.diagnostic'
import { Route as AdminDataDiagnosticRouteImport } from './routes/admin.data-diagnostic'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as StaffChecklistShiftIdRouteImport } from './routes/staff.checklist.$shiftId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicStudioQrStudioIdRouteImport } from './routes/api/public/studio-qr.$studioId'

const TrousRoute = TrousRouteImport.update({
  id: '/trous',
  path: '/trous',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosRoute = StudiosRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAppRoute = StaffAppRouteImport.update({
  id: '/staff-app',
  path: '/staff-app',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalementsRoute = SignalementsRouteImport.update({
  id: '/signalements',
  path: '/signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglesScoringRoute = ReglesScoringRouteImport.update({
  id: '/regles-scoring',
  path: '/regles-scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const PointageRoute = PointageRouteImport.update({
  id: '/pointage',
  path: '/pointage',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationRoute = FormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const DimonaRoute = DimonaRouteImport.update({
  id: '/dimona',
  path: '/dimona',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesRoute = DemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContingentsRoute = ContingentsRouteImport.update({
  id: '/contingents',
  path: '/contingents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClotureRoute = ClotureRouteImport.update({
  id: '/cloture',
  path: '/cloture',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffIdRoute = StaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAppPropositionsRoute = StaffAppPropositionsRouteImport.update({
  id: '/staff-app_/propositions',
  path: '/staff-app/propositions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningGenerateRoute = PlanningGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => PlanningRoute,
} as any)
const FormationCourseIdRoute = FormationCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => FormationRoute,
} as any)
const DisplayStudioIdRoute = DisplayStudioIdRouteImport.update({
  id: '/display/$studioId',
  path: '/display/$studioId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeederRoute = AdminSeederRouteImport.update({
  id: '/admin/seeder',
  path: '/admin/seeder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/admin/seed',
  path: '/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQaTestSuiteRoute = AdminQaTestSuiteRouteImport.update({
  id: '/admin/qa-test-suite',
  path: '/admin/qa-test-suite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrateStudiosRoute = AdminMigrateStudiosRouteImport.update({
  id: '/admin/migrate-studios',
  path: '/admin/migrate-studios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrityReportRoute = AdminIntegrityReportRouteImport.update({
  id: '/admin/integrity-report',
  path: '/admin/integrity-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHardcodingAuditRoute = AdminHardcodingAuditRouteImport.update({
  id: '/admin/hardcoding-audit',
  path: '/admin/hardcoding-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticRoute = AdminDiagnosticRouteImport.update({
  id: '/admin/diagnostic',
  path: '/admin/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataDiagnosticRoute = AdminDataDiagnosticRouteImport.update({
  id: '/admin/data-diagnostic',
  path: '/admin/data-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffChecklistShiftIdRoute = StaffChecklistShiftIdRouteImport.update({
  id: '/checklist/$shiftId',
  path: '/checklist/$shiftId',
  getParentRoute: () => StaffRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStudioQrStudioIdRoute =
  ApiPublicStudioQrStudioIdRouteImport.update({
    id: '/api/public/studio-qr/$studioId',
    path: '/api/public/studio-qr/$studioId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/checklists': typeof ChecklistsRoute
  '/cloture': typeof ClotureRoute
  '/contingents': typeof ContingentsRoute
  '/dashboard': typeof DashboardRoute
  '/demandes': typeof DemandesRoute
  '/dimona': typeof DimonaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/formation': typeof FormationRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRouteWithChildren
  '/pointage': typeof PointageRoute
  '/rapports': typeof RapportsRoute
  '/reglages': typeof ReglagesRoute
  '/regles-scoring': typeof ReglesScoringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signalements': typeof SignalementsRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-app': typeof StaffAppRoute
  '/studios': typeof StudiosRoute
  '/trous': typeof TrousRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/data-diagnostic': typeof AdminDataDiagnosticRoute
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/admin/hardcoding-audit': typeof AdminHardcodingAuditRoute
  '/admin/integrity-report': typeof AdminIntegrityReportRoute
  '/admin/migrate-studios': typeof AdminMigrateStudiosRoute
  '/admin/qa-test-suite': typeof AdminQaTestSuiteRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/seeder': typeof AdminSeederRoute
  '/display/$studioId': typeof DisplayStudioIdRoute
  '/formation/$courseId': typeof FormationCourseIdRoute
  '/planning/generate': typeof PlanningGenerateRoute
  '/staff-app/propositions': typeof StaffAppPropositionsRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/checklist/$shiftId': typeof StaffChecklistShiftIdRoute
  '/api/public/studio-qr/$studioId': typeof ApiPublicStudioQrStudioIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/checklists': typeof ChecklistsRoute
  '/cloture': typeof ClotureRoute
  '/contingents': typeof ContingentsRoute
  '/dashboard': typeof DashboardRoute
  '/demandes': typeof DemandesRoute
  '/dimona': typeof DimonaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/formation': typeof FormationRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRouteWithChildren
  '/pointage': typeof PointageRoute
  '/rapports': typeof RapportsRoute
  '/reglages': typeof ReglagesRoute
  '/regles-scoring': typeof ReglesScoringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signalements': typeof SignalementsRoute
  '/staff-app': typeof StaffAppRoute
  '/studios': typeof StudiosRoute
  '/trous': typeof TrousRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/data-diagnostic': typeof AdminDataDiagnosticRoute
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/admin/hardcoding-audit': typeof AdminHardcodingAuditRoute
  '/admin/integrity-report': typeof AdminIntegrityReportRoute
  '/admin/migrate-studios': typeof AdminMigrateStudiosRoute
  '/admin/qa-test-suite': typeof AdminQaTestSuiteRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/seeder': typeof AdminSeederRoute
  '/display/$studioId': typeof DisplayStudioIdRoute
  '/formation/$courseId': typeof FormationCourseIdRoute
  '/planning/generate': typeof PlanningGenerateRoute
  '/staff-app/propositions': typeof StaffAppPropositionsRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff': typeof StaffIndexRoute
  '/staff/checklist/$shiftId': typeof StaffChecklistShiftIdRoute
  '/api/public/studio-qr/$studioId': typeof ApiPublicStudioQrStudioIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/checklists': typeof ChecklistsRoute
  '/cloture': typeof ClotureRoute
  '/contingents': typeof ContingentsRoute
  '/dashboard': typeof DashboardRoute
  '/demandes': typeof DemandesRoute
  '/dimona': typeof DimonaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/formation': typeof FormationRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRouteWithChildren
  '/pointage': typeof PointageRoute
  '/rapports': typeof RapportsRoute
  '/reglages': typeof ReglagesRoute
  '/regles-scoring': typeof ReglesScoringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signalements': typeof SignalementsRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-app': typeof StaffAppRoute
  '/studios': typeof StudiosRoute
  '/trous': typeof TrousRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/data-diagnostic': typeof AdminDataDiagnosticRoute
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/admin/hardcoding-audit': typeof AdminHardcodingAuditRoute
  '/admin/integrity-report': typeof AdminIntegrityReportRoute
  '/admin/migrate-studios': typeof AdminMigrateStudiosRoute
  '/admin/qa-test-suite': typeof AdminQaTestSuiteRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/seeder': typeof AdminSeederRoute
  '/display/$studioId': typeof DisplayStudioIdRoute
  '/formation/$courseId': typeof FormationCourseIdRoute
  '/planning/generate': typeof PlanningGenerateRoute
  '/staff-app_/propositions': typeof StaffAppPropositionsRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/checklist/$shiftId': typeof StaffChecklistShiftIdRoute
  '/api/public/studio-qr/$studioId': typeof ApiPublicStudioQrStudioIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/checklists'
    | '/cloture'
    | '/contingents'
    | '/dashboard'
    | '/demandes'
    | '/dimona'
    | '/feedbacks'
    | '/formation'
    | '/login'
    | '/notifications'
    | '/planning'
    | '/pointage'
    | '/rapports'
    | '/reglages'
    | '/regles-scoring'
    | '/reset-password'
    | '/signalements'
    | '/staff'
    | '/staff-app'
    | '/studios'
    | '/trous'
    | '/admin/audit'
    | '/admin/data-diagnostic'
    | '/admin/diagnostic'
    | '/admin/hardcoding-audit'
    | '/admin/integrity-report'
    | '/admin/migrate-studios'
    | '/admin/qa-test-suite'
    | '/admin/seed'
    | '/admin/seeder'
    | '/display/$studioId'
    | '/formation/$courseId'
    | '/planning/generate'
    | '/staff-app/propositions'
    | '/staff/$id'
    | '/staff/'
    | '/staff/checklist/$shiftId'
    | '/api/public/studio-qr/$studioId'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation'
    | '/checklists'
    | '/cloture'
    | '/contingents'
    | '/dashboard'
    | '/demandes'
    | '/dimona'
    | '/feedbacks'
    | '/formation'
    | '/login'
    | '/notifications'
    | '/planning'
    | '/pointage'
    | '/rapports'
    | '/reglages'
    | '/regles-scoring'
    | '/reset-password'
    | '/signalements'
    | '/staff-app'
    | '/studios'
    | '/trous'
    | '/admin/audit'
    | '/admin/data-diagnostic'
    | '/admin/diagnostic'
    | '/admin/hardcoding-audit'
    | '/admin/integrity-report'
    | '/admin/migrate-studios'
    | '/admin/qa-test-suite'
    | '/admin/seed'
    | '/admin/seeder'
    | '/display/$studioId'
    | '/formation/$courseId'
    | '/planning/generate'
    | '/staff-app/propositions'
    | '/staff/$id'
    | '/staff'
    | '/staff/checklist/$shiftId'
    | '/api/public/studio-qr/$studioId'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/activation'
    | '/checklists'
    | '/cloture'
    | '/contingents'
    | '/dashboard'
    | '/demandes'
    | '/dimona'
    | '/feedbacks'
    | '/formation'
    | '/login'
    | '/notifications'
    | '/planning'
    | '/pointage'
    | '/rapports'
    | '/reglages'
    | '/regles-scoring'
    | '/reset-password'
    | '/signalements'
    | '/staff'
    | '/staff-app'
    | '/studios'
    | '/trous'
    | '/admin/audit'
    | '/admin/data-diagnostic'
    | '/admin/diagnostic'
    | '/admin/hardcoding-audit'
    | '/admin/integrity-report'
    | '/admin/migrate-studios'
    | '/admin/qa-test-suite'
    | '/admin/seed'
    | '/admin/seeder'
    | '/display/$studioId'
    | '/formation/$courseId'
    | '/planning/generate'
    | '/staff-app_/propositions'
    | '/staff/$id'
    | '/staff/'
    | '/staff/checklist/$shiftId'
    | '/api/public/studio-qr/$studioId'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationRoute: typeof ActivationRoute
  ChecklistsRoute: typeof ChecklistsRoute
  ClotureRoute: typeof ClotureRoute
  ContingentsRoute: typeof ContingentsRoute
  DashboardRoute: typeof DashboardRoute
  DemandesRoute: typeof DemandesRoute
  DimonaRoute: typeof DimonaRoute
  FeedbacksRoute: typeof FeedbacksRoute
  FormationRoute: typeof FormationRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PlanningRoute: typeof PlanningRouteWithChildren
  PointageRoute: typeof PointageRoute
  RapportsRoute: typeof RapportsRoute
  ReglagesRoute: typeof ReglagesRoute
  ReglesScoringRoute: typeof ReglesScoringRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignalementsRoute: typeof SignalementsRoute
  StaffRoute: typeof StaffRouteWithChildren
  StaffAppRoute: typeof StaffAppRoute
  StudiosRoute: typeof StudiosRoute
  TrousRoute: typeof TrousRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDataDiagnosticRoute: typeof AdminDataDiagnosticRoute
  AdminDiagnosticRoute: typeof AdminDiagnosticRoute
  AdminHardcodingAuditRoute: typeof AdminHardcodingAuditRoute
  AdminIntegrityReportRoute: typeof AdminIntegrityReportRoute
  AdminMigrateStudiosRoute: typeof AdminMigrateStudiosRoute
  AdminQaTestSuiteRoute: typeof AdminQaTestSuiteRoute
  AdminSeedRoute: typeof AdminSeedRoute
  AdminSeederRoute: typeof AdminSeederRoute
  DisplayStudioIdRoute: typeof DisplayStudioIdRoute
  StaffAppPropositionsRoute: typeof StaffAppPropositionsRoute
  ApiPublicStudioQrStudioIdRoute: typeof ApiPublicStudioQrStudioIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trous': {
      id: '/trous'
      path: '/trous'
      fullPath: '/trous'
      preLoaderRoute: typeof TrousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios': {
      id: '/studios'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof StudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-app': {
      id: '/staff-app'
      path: '/staff-app'
      fullPath: '/staff-app'
      preLoaderRoute: typeof StaffAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signalements': {
      id: '/signalements'
      path: '/signalements'
      fullPath: '/signalements'
      preLoaderRoute: typeof SignalementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regles-scoring': {
      id: '/regles-scoring'
      path: '/regles-scoring'
      fullPath: '/regles-scoring'
      preLoaderRoute: typeof ReglesScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pointage': {
      id: '/pointage'
      path: '/pointage'
      fullPath: '/pointage'
      preLoaderRoute: typeof PointageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation': {
      id: '/formation'
      path: '/formation'
      fullPath: '/formation'
      preLoaderRoute: typeof FormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimona': {
      id: '/dimona'
      path: '/dimona'
      fullPath: '/dimona'
      preLoaderRoute: typeof DimonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes': {
      id: '/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof DemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contingents': {
      id: '/contingents'
      path: '/contingents'
      fullPath: '/contingents'
      preLoaderRoute: typeof ContingentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloture': {
      id: '/cloture'
      path: '/cloture'
      fullPath: '/cloture'
      preLoaderRoute: typeof ClotureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$id': {
      id: '/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof StaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff-app_/propositions': {
      id: '/staff-app_/propositions'
      path: '/staff-app/propositions'
      fullPath: '/staff-app/propositions'
      preLoaderRoute: typeof StaffAppPropositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/generate': {
      id: '/planning/generate'
      path: '/generate'
      fullPath: '/planning/generate'
      preLoaderRoute: typeof PlanningGenerateRouteImport
      parentRoute: typeof PlanningRoute
    }
    '/formation/$courseId': {
      id: '/formation/$courseId'
      path: '/$courseId'
      fullPath: '/formation/$courseId'
      preLoaderRoute: typeof FormationCourseIdRouteImport
      parentRoute: typeof FormationRoute
    }
    '/display/$studioId': {
      id: '/display/$studioId'
      path: '/display/$studioId'
      fullPath: '/display/$studioId'
      preLoaderRoute: typeof DisplayStudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seeder': {
      id: '/admin/seeder'
      path: '/admin/seeder'
      fullPath: '/admin/seeder'
      preLoaderRoute: typeof AdminSeederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seed': {
      id: '/admin/seed'
      path: '/admin/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qa-test-suite': {
      id: '/admin/qa-test-suite'
      path: '/admin/qa-test-suite'
      fullPath: '/admin/qa-test-suite'
      preLoaderRoute: typeof AdminQaTestSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migrate-studios': {
      id: '/admin/migrate-studios'
      path: '/admin/migrate-studios'
      fullPath: '/admin/migrate-studios'
      preLoaderRoute: typeof AdminMigrateStudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrity-report': {
      id: '/admin/integrity-report'
      path: '/admin/integrity-report'
      fullPath: '/admin/integrity-report'
      preLoaderRoute: typeof AdminIntegrityReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hardcoding-audit': {
      id: '/admin/hardcoding-audit'
      path: '/admin/hardcoding-audit'
      fullPath: '/admin/hardcoding-audit'
      preLoaderRoute: typeof AdminHardcodingAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostic': {
      id: '/admin/diagnostic'
      path: '/admin/diagnostic'
      fullPath: '/admin/diagnostic'
      preLoaderRoute: typeof AdminDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-diagnostic': {
      id: '/admin/data-diagnostic'
      path: '/admin/data-diagnostic'
      fullPath: '/admin/data-diagnostic'
      preLoaderRoute: typeof AdminDataDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/checklist/$shiftId': {
      id: '/staff/checklist/$shiftId'
      path: '/checklist/$shiftId'
      fullPath: '/staff/checklist/$shiftId'
      preLoaderRoute: typeof StaffChecklistShiftIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/studio-qr/$studioId': {
      id: '/api/public/studio-qr/$studioId'
      path: '/api/public/studio-qr/$studioId'
      fullPath: '/api/public/studio-qr/$studioId'
      preLoaderRoute: typeof ApiPublicStudioQrStudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FormationRouteChildren {
  FormationCourseIdRoute: typeof FormationCourseIdRoute
}

const FormationRouteChildren: FormationRouteChildren = {
  FormationCourseIdRoute: FormationCourseIdRoute,
}

const FormationRouteWithChildren = FormationRoute._addFileChildren(
  FormationRouteChildren,
)

interface PlanningRouteChildren {
  PlanningGenerateRoute: typeof PlanningGenerateRoute
}

const PlanningRouteChildren: PlanningRouteChildren = {
  PlanningGenerateRoute: PlanningGenerateRoute,
}

const PlanningRouteWithChildren = PlanningRoute._addFileChildren(
  PlanningRouteChildren,
)

interface StaffRouteChildren {
  StaffIdRoute: typeof StaffIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffChecklistShiftIdRoute: typeof StaffChecklistShiftIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIdRoute: StaffIdRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffChecklistShiftIdRoute: StaffChecklistShiftIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationRoute: ActivationRoute,
  ChecklistsRoute: ChecklistsRoute,
  ClotureRoute: ClotureRoute,
  ContingentsRoute: ContingentsRoute,
  DashboardRoute: DashboardRoute,
  DemandesRoute: DemandesRoute,
  DimonaRoute: DimonaRoute,
  FeedbacksRoute: FeedbacksRoute,
  FormationRoute: FormationRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PlanningRoute: PlanningRouteWithChildren,
  PointageRoute: PointageRoute,
  RapportsRoute: RapportsRoute,
  ReglagesRoute: ReglagesRoute,
  ReglesScoringRoute: ReglesScoringRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignalementsRoute: SignalementsRoute,
  StaffRoute: StaffRouteWithChildren,
  StaffAppRoute: StaffAppRoute,
  StudiosRoute: StudiosRoute,
  TrousRoute: TrousRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDataDiagnosticRoute: AdminDataDiagnosticRoute,
  AdminDiagnosticRoute: AdminDiagnosticRoute,
  AdminHardcodingAuditRoute: AdminHardcodingAuditRoute,
  AdminIntegrityReportRoute: AdminIntegrityReportRoute,
  AdminMigrateStudiosRoute: AdminMigrateStudiosRoute,
  AdminQaTestSuiteRoute: AdminQaTestSuiteRoute,
  AdminSeedRoute: AdminSeedRoute,
  AdminSeederRoute: AdminSeederRoute,
  DisplayStudioIdRoute: DisplayStudioIdRoute,
  StaffAppPropositionsRoute: StaffAppPropositionsRoute,
  ApiPublicStudioQrStudioIdRoute: ApiPublicStudioQrStudioIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
